config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages do
    resources :comments
  end

  root 'messages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]


    before_action :find_message, only: [:create, :edit, :update, :destroy]
    before_action :find_comment, only: [:edit, :update, :destroy]

    def create
        @comment = @message.comments.build(comment_params)
        @comment.user_id = current_user.id

        if @comment.save
            redirect_to message_path(@message)
        else 
            render 'new'
        end
    end

    def edit 
    end

    def update
        if @comment.update(comment_params)
            redirect_to message_path(@message)
        else
            render 'edit'
        end
    end

    def destroy
        @comment.destroy
        redirect_to message_path(@message)
    end



    private
    def comment_params
        params.require(:comment).permit(:user_id, :content)
    end

    def find_message
        @message = Message.find(params[:message_id])
    end

    def find_comment
        @comment = @message.comments.find(params[:id])
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

    before_action :authenticate_user!, except: [:index, :show]

    before_action :find_message, only: [:show, :edit, :update, :destroy]

    def index 
        @messages = Message.all
    end

    def show 
    end

    def new
        @message = Message.new 
    end

    def create
        @message = current_user.messages.new(message_params)

         respond_to do |format|
            if @message.save
              format.html { redirect_to @message, warning: 'Mensaje Creado Exitosamente.' }
              format.json { render :show, status: :created, location: @message }
            else
              format.html { render :new }
              format.json { render json: @message.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, warning: 'Mensaje actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
    end

    def edit 
    end

    def destroy
        @message.destroy
        respond_to do |format|
            format.html { redirect_to messages_url, warning: 'Mensaje Borrado Exitosamente.' }
            format.json { head :no_content }
        end
    end




    private
        def find_message
            @message = Message.find(params[:id])
        end

        def message_params
            params.require(:message).permit(:title, :description)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
    <p class="comment-content"><%= comment.content %></p>
    <p class="comment-posted-by">Por: <%= comment.user.email %> <%= time_ago_in_words(comment.created_at)%></p>

    <div class="links">
        <% if user_signed_in? %>
            <% if comment.user_id == current_user.id %>
                <%= link_to "Editar", edit_message_comment_path(comment.message, comment), class: "btn btn-success" %>
                <%= link_to "Eliminar", message_comment_path(comment.message, comment), method: :delete, data: { confirm: "Estas Seguro"}, class: "btn btn-warning" %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for ([@message, @message.comments.build]) do |f| %>
    <div class="form-group">
        <%= f.input :content, label: false, placeholder: "Comentario", input_html: { class: "form-control alto" } %>
    </div>
  <%= f.button :submit, "Postear Comentario", class: "btn btn-primary" %>
<% end %>

app/views/comments/edit.html.erb
<div class="container mt-3">
        <h1>Editar</h1>
    <%= simple_form_for ([@message, @comment]) do |f| %>
        <div class="form-group">
            <%= f.input :content, label: false, placeholder: "Comentario", input_html: { class: "form-control alto" } %>
        </div>
    <%= f.button :submit, "Postear Comentario", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Espn Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'partials/navbar'%>
    <%= render 'partials/notificaciones'%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
    <div class="form-group">
        <%= f.input :title, label: false, placeholder: "Titulo", input_html: { class: "form-control" } %>
    </div>
    <div class="form-group">
         <%= f.input :description, label: false, placeholder: "Descripcion", input_html: { class: "form-control alto" } %>
    </div>
 
  <%= f.button :submit, "Postear Mensaje", class: "btn btn-primary" %>
<% end %>

app/views/messages/edit.html.erb
<div class="container">
        <div class="col-md-8 mt-3  col-md-offset-2">
            <h1 class="new-msg-header">Editar Mensaje</h1>
            <%=render 'form'%>
        </div>
</div>

app/views/messages/index.html.erb
<% @messages.each do |message|%>
    <div class="col-md-10 col-md-offset-1 mt-5">
        <div class="message">
            <h2 class="message-title"><%= message.title %></h2>
            <%= link_to "Unirse A Conversacion ", message, class: "btn-custom" %>
        </div>
    </div>
<% end %>

app/views/messages/new.html.erb
<div class="container">
        <div class="col-md-8 mt-3  col-md-offset-2">
            <h1 class="new-msg-header">Postear Mensaje</h1>
            <%=render 'form'%>
        </div>
</div>

app/views/messages/show.html.erb
<div class="col-md-10 col-md-offset-1 mt-3 mb-3">
    <div class="message-show">
        <h2><%= @message.title %></h2>
        <p class="message-posted-by"><%= time_ago_in_words(@message.created_at) %> </p>
        <p class="message-desc"><%= @message.description %></p>

        <h3 class="comment-section-header">Comentarios:</h3>
        <p><%= render @message.comments %></p>

        <h3 class="reply-to-msg">Unirse A Discusion </h3>
        <%= render 'comments/form'%>

        <div class="links btn-group">
            <% if user_signed_in? %>
                <% if @message.user_id == current_user.id %>
                    <%= link_to "Editar", edit_message_path(@message), class: "btn btn-success"%>
                    <%= link_to "Borrar", message_path(@message), method: :delete, data: { confirm: "Estas Seguro"}, class: "btn btn-danger ml-2"%>
                <% end %>
            <% end %>
            <%= link_to "Atras", root_path, class: "btn btn-info ml-2" %>
        </div>
    </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <%= link_to "ESPN FAN FORUM", root_path, class: "navbar-brand"%>
        </div>
        <ul class="navbar-nav nav navbar-right">
            <% if user_signed_in? %>
                <li><%= link_to "Desloguearse", destroy_user_session_path, method: :delete %></li>
            <% else %>
                <div class="row">
                    <li><%= link_to "Inicia Sesion", new_user_session_path, class: "ml-2" %></li>
                    <li><%= link_to "Registrarte", new_user_registration_path, class: "ml-2" %></li>
                </div>
            <% end %>
        </ul>
        <% if user_signed_in? %>
            <div><%= link_to "Nuevo Post", new_message_path, class: "navbar-text navbar-link"%></div>
        <% end %>
    </div>
</nav>

app/views/partials/_notificaciones.html.erb
<% flash.each do |name, msg| %>
      <div class="alert alert-dismissible alert-<%= name %>">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h4 class="alert-heading"><%= msg %></h4>
      </div>
    <%end%>